// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoiJeVlczHQEHglVxhCj3IvfjbBt8v4zY',
    appId: '1:1069489323213:web:243d28ca427bbfec10bd84',
    messagingSenderId: '1069489323213',
    projectId: 'ems-app-710ec',
    authDomain: 'ems-app-710ec.firebaseapp.com',
    storageBucket: 'ems-app-710ec.appspot.com',
    measurementId: 'G-TTNS6256S3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa5cHF7He0XjWk0hgESX6YbaocgmD-fbk',
    appId: '1:1069489323213:android:4c9e9b025348464d10bd84',
    messagingSenderId: '1069489323213',
    projectId: 'ems-app-710ec',
    storageBucket: 'ems-app-710ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCebqNGFGOkTENdQIXvgS5Y2SpX82BdUl0',
    appId: '1:1069489323213:ios:2804784e2f53ccb610bd84',
    messagingSenderId: '1069489323213',
    projectId: 'ems-app-710ec',
    storageBucket: 'ems-app-710ec.appspot.com',
    androidClientId: '1069489323213-5b2pt1l9i35nolvrse9klvo8na1gll4k.apps.googleusercontent.com',
    iosClientId: '1069489323213-3378mo3449cc14ef18fk1sm977asi1oo.apps.googleusercontent.com',
    iosBundleId: 'com.example.digitalHealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCebqNGFGOkTENdQIXvgS5Y2SpX82BdUl0',
    appId: '1:1069489323213:ios:2804784e2f53ccb610bd84',
    messagingSenderId: '1069489323213',
    projectId: 'ems-app-710ec',
    storageBucket: 'ems-app-710ec.appspot.com',
    androidClientId: '1069489323213-5b2pt1l9i35nolvrse9klvo8na1gll4k.apps.googleusercontent.com',
    iosClientId: '1069489323213-3378mo3449cc14ef18fk1sm977asi1oo.apps.googleusercontent.com',
    iosBundleId: 'com.example.digitalHealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUlEpxsyodM5afmyIN0b6894Arz3HSZgA',
    appId: '1:1069489323213:web:2e47de8779cb3d4910bd84',
    messagingSenderId: '1069489323213',
    projectId: 'ems-app-710ec',
    authDomain: 'ems-app-710ec.firebaseapp.com',
    storageBucket: 'ems-app-710ec.appspot.com',
    measurementId: 'G-BW65RHEBQE',
  );
}
